# Generated by Django 4.1.2 on 2022-10-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_category_product_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
