# Generated by Django 4.1.2 on 2022-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_iamge_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
