# Generated by Django 4.1.2 on 2022-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contect_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect_us',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
