# Generated by Django 4.1.2 on 2022-10-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_order_datetime_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
