# Generated by Django 4.1.2 on 2022-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
